### ISSUE TITLE
Salyx Wood Slab recipe error.

### ISSUE THREAD

**Issue by cHaOZZoNE** [elytra/Unabridged#506]
**Issue Description:**
Salyx woodslabs (1163:3) from Ancient Trees are not made by using Salyx planks (1177) but rather of Delnas Planks (1148:3). Right now the recipe produces regular woodslabs when Salyx planks are used.

**Steps to Reproduce:**
Attempt to make Salyx Slabs with Salyx planks.

**Comment by adegarimore** [comment]
Fixed in R14
