### ISSUE TITLE
Slider Dungeon Crash

### ISSUE THREAD

**Issue by TheNetherFires** [elytra/Unabridged#511]
So, I was going to my slider dungeon to start building a base, and it proceeds to crash me when I use my mining laser. 

Steps to reproduce this is as follows: Go into a conquered Slider Dungeon, and start using a wide mining laser with a diameter of 9 and depth of 3.

Crash Report: http://paste.ubuntu.com/23076547/

**Comment by BBoldt** [comment]
Have you done anything with the wireless redstone mod there?

That seems to be what is causing the crash.

**Comment by BBoldt** [comment]
Fixed in 3.18, Aether II was replaced with The Aether.

https://www.reddit.com/r/MinecraftUnabridged/comments/khe9qz/unabridged_315_318_new_ars_magica_2_ic2_classic/
